onjiro_kakeibo:
    resource: "@OnjiroKakeiboBundle/Controller/"
    type:     annotation
    prefix:   /

onjiro_session:
    resource: "@OnjiroSessionBundle/Resources/config/routing.yml"
    prefix:   /

