parameters:
    # とりあえずここに書いているがあとで config.yml に移す
    onjiro_kakeibo.formatMappings:
        '/kakeibo.*': twig
        '/api.*': json
    # フォーマッターは別途タイプ毎に切り出す形としたい
    onjiro_kakeibo.formatters:
        twig: Onjiro\Bundle\KakeiboBundle\Formatter\TwigFormatter
        json: Onjiro\Bundle\KakeiboBundle\Formatter\JsonFormatter

services:
    kernel.listener.your_listener_name:
        class: Onjiro\Bundle\KakeiboBundle\EventListener\ViewEventListener
        arguments: 
            - %onjiro_kakeibo.formatMappings%
            - %onjiro_kakeibo.formatters%
            - @templating
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onViewEvent }

    database.hoge:
        class: Onjiro\Bundle\KakeiboBundle\Database\DatabaseConnectorBase
        arguments:
            - test_table
            - @doctrine.dbal.default_connection
