parameters:
#    onjiro_session.example.class: Onjiro\Bundle\SessionBundle\Example

services:
#    onjiro_session.example:
#        class: %onjiro_session.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
